# Generated by Django 5.1.6 on 2025-02-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '图书分类', 'verbose_name_plural': '图书分类'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='分类编码'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='父级分类'),
        ),
        migrations.AddField(
            model_name='category',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=1, verbose_name='可用数量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='borrowed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借阅者'),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='是否归还'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books_book',
        ),
        migrations.AlterModelTable(
            name='bookborrowing',
            table='books_bookborrowing',
        ),
        migrations.AlterModelTable(
            name='category',
            table='books_category',
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment', models.TextField(verbose_name='评论')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '图书评论',
                'verbose_name_plural': '图书评论',
                'db_table': 'books_bookcomment',
            },
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('reason', models.TextField(blank=True, verbose_name='推荐理由')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='推荐者')),
            ],
            options={
                'verbose_name': '图书推荐',
                'verbose_name_plural': '图书推荐',
                'db_table': 'books_bookrecommendation',
            },
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('reservationer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约者')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'books_bookreservation',
            },
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='归还时间')),
                ('returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('returner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归还者')),
            ],
            options={
                'verbose_name': '归还记录',
                'verbose_name_plural': '归还记录',
                'db_table': 'books_bookreturn',
            },
        ),
    ]
